language: elixir
notifications:
  recipients:
    - eduardo@gurgel.me
otp_release:
  - 17.0
  - 17.1
  - 17.3
elixir:
  - 1.0.0
  - 1.0.1
env:
  - MIX_ENV=test
script:
  - mix test --no-start
  - mix dogma
