language: elixir
notifications:
  recipients:
    - eduardo@gurgel.me
otp_release:
  - 17.4
  - 17.5
  - 18.0
elixir:
  - 1.0.4
  - 1.0.5
env:
  - MIX_ENV=test
script:
  - mix test --no-start
  - mix dogma
